---
development:
  cloud_name: natalijastepurko
  api_key: '172643936862137'
  api_secret: hF9Nm_plQqMw7oP973BybV6dm3w
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: natalijastepurko
  api_key: '172643936862137'
  api_secret: hF9Nm_plQqMw7oP973BybV6dm3w
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: natalijastepurko
  api_key: '172643936862137'
  api_secret: hF9Nm_plQqMw7oP973BybV6dm3w
  enhance_image_tag: true
  static_file_support: false
